language: node_js

node_js:
  - stable

install:
  - npm install
  - typings install

script:
  - npm test

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email: false
